# Generated by Django 5.1.3 on 2024-12-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_options_customerdetails_medicineorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='state',
            field=models.CharField(choices=[('CHAT', 'Chat'), ('PRESCRIPTION_REVIEW', 'Prescription Review'), ('ORDER_QUANTITY', 'Order Quantity'), ('COLLECT_INFO', 'Collect Info'), ('CONFIRM_ORDER', 'Confirm Order'), ('ORDER_COMPLETE', 'Order Complete'), ('MANUAL_REVIEW', 'Manual Review')], default='CHAT', max_length=50),
        ),
    ]
